#!/bin/bash

# Script para ayudar a obtener las claves de Supabase

echo ""
echo "========================================="
echo "  OBTENER CLAVES DE SUPABASE"
echo "========================================="
echo ""
echo "Sigue estos pasos:"
echo ""
echo "1. Abre este link en tu navegador:"
echo "   👉 https://supabase.com/dashboard/project/ygvzkfotrdqyehiqljle/settings/api"
echo ""
echo "2. Busca esta clave:"
echo ""
echo "   'Secret key' (default)"
echo "      - La verás en la sección 'Secret keys'"
echo "      - Click en el icono de ojo para revelarla"
echo "      - ⚠️  Esta es SECRETA, no la compartas"
echo "      - Empieza con: sb_secret_..."
echo ""
echo "3. Actualiza el archivo .env con esta clave:"
echo "   - SUPABASE_SECRET_KEY=\"clave_copiada\""
echo ""
echo "Nota: Las demás claves ya están configuradas:"
echo "   ✅ NEXT_PUBLIC_SUPABASE_URL"
echo "   ✅ NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
echo ""
echo "========================================="
echo ""
read -p "Presiona ENTER cuando hayas copiado las claves..."
echo ""
echo "✅ Ahora edita el archivo .env y reemplaza los valores"
echo ""
echo "Puedes usar:"
echo "  nano .env"
echo "  o"
echo "  code .env"
echo ""
